language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: j3V6DcUPZQW2ttthkAAQD6/JP9fj3kDUyQ3S3zbrs2M8nPo6NkUIDl4tPlzc2FKIXYrkHczx1g367avhODlu3DINIavYr9ofaJQO/vlIEaO+qeIFsUIV7gRz0xEmS4Bm0QtEm5Lny6tNw0eL+h7I9vwFZF9xfqd8Cp6fmmlScK2igH4b8Wps+YrvBz/3ikzpQj1Qq8I3oZSfhf+oGhHl0sFdb09yBpjAyvnrbiVtc5TqYMmsJ7wzvX52A5prxxdKAc2TBDfMGXSUKHbp/pnzJG9nTKPcgiy0IXGi+QC4aOpP98ciUYJg+FUlOpnF3V3OqjGUQmMCw1Yr3wNZKMu8Mzd9wE++mXI6OqUToeiBZlQ7eFNRe/zhsRpKyB99l96AiASxwkddU0/M6Wo2Cha8arrK+6XN2hMNR47kTsBGCVEeeclFUcsW40JPWKrzr+ZAxwGq3XuBcG3TDnYdAiSF7kpAs/HA3dm20RggWQVKTfgiEGmcpohuvNxS5tWKEbpW1hhKOosSyYbiIf+RGuAi3CpUmJL/1eIzAHkwKhf9giHtBUGEQD51Ilnx6o/fQqKPFKjAyL/5Y3UZWO0sweMM/mWus9Y1+DpJYwrmCd7YX7ujrCpsvXGJeg26v2KidNX6y+oTSeWyw/x2QCavKAYwtGYOF/P2iEAGqpPBp7AgCLc=
#  file: DayNightTerminator-1.0-RELEASE.jar
#  file: DayNightTerminator-1.0-RELEASE.pom
  file: target/DayNightTerminator-1.0-RELEASE.jar
  skip_cleanup: true
  on:
    repo: JamesGosling/DayNightTerminator
    all_branches: true
    tags: true
env:
  global:
    - SONATYPE_USERNAME=jag@nighthacks.com
    - secure: "LXH5AX8kYsOAg94QzCEnxwS+aNowJ6WVd/7nxRhCr/9+q7RyOFQy8mBMHahBMHIgtsrw8/fp/oR78Ou/IGUvdQhMVRvclG+p9ij2UuRAGMrRih8abeZvHoo9m5eVLAxMd/ZfKKdF2piogCiFncko/YzayamNS49//0qskIXFAPhpt1JFeil4kDRRsFe4AJK2KviwvMOEt4Qr1CRrgnL1OyZ/BaniaFGx4ZUrPABUAb+wHwGIE+qV19PcZIDtlmST1haUtFoSMFD1OHzZ/S39oHsTY5N8KXvoZbiVhB5C4138IzNPE16TfbFTfQWfUFApOiJrljfmU7zJGDXecukcarC5gl9TTniAEn0/30yM0vjPgzPofSSqAd2yoaxW9W0KUK8WwLXydvBHkIJu33tII5OHnBOLM1EvIIdRvbliXWIgJnd+rqAY3d0Sd8847EqFI8dD0zrwUpxDCE0In7jMtU8GPhomaypyHOEo/wLgJKo9MxAgpJIFtWDR6OMkLsWiXTcMkGCUNMbZ8tAr7CPMJkfx46dYRpGly4Rdy8SYv78K2bO48Aj3N0BXNef7QjjX8wLQqCcCtXYx9yUGWDysp4otz0KGvv24EU8cHFYifuF8a7xfH8cYw3+/KtsjhuRIOnCHD8zT/kWldkJmIDps3nbiiWUb5YBvu5YmHUc56ak="
after_success:
  - python addServer.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml
